### ISSUE TITLE
System.OutOfMemoryException when loading existing save

### ISSUE THREAD

**Issue by mickdekkers** [ConfuzzedCat/TerrariaInjector#3]
When I try to load my existing world through TerrariaInjector, it always crashes with a `System.OutOfMemoryException`.
This is quite odd, because:
- I'm certain it does in fact have plenty of free memory available at the time of the crash (at least 10 GB)
  - Terraria's peak memory usage with that save is 1.4GB for me
  - TerrariaInjector's peak memory usage only hits around 1.2GB while loading the world before it crashes
- Terraria without TerrariaInjector doesn't crash on the same world
- I've also been testing TerrariaInjector with a small Journey world and that loads without a problem

![image](https://user-images.githubusercontent.com/5085260/208308417-2ef797eb-65e6-42e5-a147-3acb5f83d217.png)

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at ReLogic.Graphics.DynamicSpriteFont.InternalDraw(String text, SpriteBatch spriteBatch, Vector2 startPosition, Color color, Single rotation, Vector2 origin, Vector2& scale, SpriteEffects spriteEffects, Single depth)
at Terraria.Main.DrawVersionNumber_Patch1(Color menuColor, Single upBump)
at Terraria.Main.DrawMenu(GameTime gameTime)
at Terraria.Main.DoDraw(GameTime gameTime)
at Terraria.Main.Draw(GameTime gameTime)
at Microsoft.Xna.Framework.Game.DrawFrame()
at Microsoft.Xna.Framework.Game.Tick()
at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
at Microsoft.Xna.Framework.GameHost.Onldle()
at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at Microsoft.Xna.Framework.WindowsGameHost.Run()
at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
at Terraria.Program.RunGame()
```

I've uploaded both the save that's failing to load and the working Journey save for comparison:

[crashing-save.zip](https://github.com/ConfuzzedCat/TerrariaInjector/files/10254303/crashing-save.zip)
[working-save.zip](https://github.com/ConfuzzedCat/TerrariaInjector/files/10254304/working-save.zip)

Version info:
```
Terraria 1.4.4.9
TerrariaInjector 1.1.0
Windows 10 64-bit
```

This one's a bit of a mystery to me, but then again I'm not that familiar with .NET myself. I'm curious if someone could reproduce the issue on their end using the saves I uploaded, or if it's something to do with my machine.

Thanks either way! This is quite an interesting project and I've already learned a bit about code injection and Harmony by reading the source code.

**Comment by ConfuzzedCat** [comment]
First thank you for the all the info. I will take a look at it soonish.

**Comment by ConfuzzedCat** [comment]
Ok after some testing, this has nothing to do my previous assumption, but rather the size of the world.
My guess is that something in the Terraria's Main's constructor is allowing to load bigger worlds, which isn't getting set correcting when harmony is inject/patching the code into the assembly.

**Comment by ConfuzzedCat** [comment]
I will have to put a little hold on fixing this, while I'm dealing with exams and other stuff.

**Comment by mickdekkers** [comment]
That's totally understandable, thanks for looking into it so far 😄

**Comment by Expmeow** [comment]
The same problem...
Please fix it soon XD

**Comment by Expmeow** [comment]
Now we can only play it with a small world😂

**Comment by ConfuzzedCat** [comment]
So I have for most of the day to fix the issue, but sadly im not any closer, or i don't think im. I thought it had something to do with the patching touching the static main in terraria and that messing with some settings or something, but after fixing that (making the mod patching happen after the static main is constructed) and still having the issue. So now, i still have no idea, where the issue lies. I will try and ask around and see if any knows what may be causing the issue (cause I found that the out of memory happens at random location in the code). I will push the other fix soon, and then start looking into again some time next week maybe.

**Comment by ConfuzzedCat** [comment]
So.. I have an update. I tried to change the terraria.exe to load an library that will do the injection and it works, without causing the OutOfMemory bug.. The only issue is that, that I had to modify the game itself...

**Comment by ConfuzzedCat** [comment]
Alright, I have some more news. I have found a way to inject code into terraria without modifying the exe... the bad news are that it requires another exe to inject my injector into Terraria and then patch it. 
https://github.com/jonatan1024/clrinject

**Comment by deltaone** [comment]
> So.. I have an update. I tried to change the terraria.exe to load an library that will do the injection and it works, without causing the OutOfMemory bug.. The only issue is that, that I had to modify the game itself...
Can show what you modify ? Maybe rewrite code to path game itself and apply Harmony patches with start terraria.exe through linked library ?

**Comment by ConfuzzedCat** [comment]
I don't think i have the modified binary anymore, but I wrote a method that loaded Harmony first and then TerrariaInjector, and then invoked the patching method. The method would be ran after the other dependencies was loaded(Don't remember the method name).

**Comment by deltaone** [comment]
You can publish sources of TerrariaInjectorLib.dll, thx!

**Comment by ConfuzzedCat** [comment]
> You can publish sources of TerrariaInjectorLib.dll, thx!

Here you go:
https://gist.github.com/ConfuzzedCat/33fccb7c7996d95ae33c04d2afb2cae2

**Comment by deltaone** [comment]
![2023-03-07_222725](https://user-images.githubusercontent.com/822865/223516514-2595a007-180e-4058-b14c-b2c12aadd255.png)
![2023-03-07_222742](https://user-images.githubusercontent.com/822865/223516544-25e4eeb6-1a77-4594-a0a3-161e8e10d09c.png)
[~mod-injector.zip](https://github.com/ConfuzzedCat/TerrariaInjector/files/10912827/mod-injector.zip)

Try set these project settings - Any CPU / 32 bit preferred and exception out of memory on create large world would gone ...
Test project in attachments, simply copy terraria folder contents to bin folder ...

**Comment by ConfuzzedCat** [comment]
Little update, I havent forgot this: I have been testing and trying off-time. Other than using the clrinject-cli or modifying the exe, I haven't had any luck. 
@deltaone your solution didn't seem to work sadly.. (and it also required me to change to net4.5+). If you I'm wrong and you got it to work, with the worlds mick sent, then feel free to correct me.

**Comment by deltaone** [comment]
This is rewrite of Confuzzedcat TerrariaInjector
Added/changed: 
   injector can now work with any xna/.net application (Stardew Valley on example)
   new callable mod function - PrePatch(AssemblyDefinition) - chained runtime assembly modification with Cecil
   workaround for issue https://github.com/ConfuzzedCat/TerrariaInjector/issues/3
   added mod compile system (compile mods through csc.exe)
   added mods for Terraria.v1.4.4.9v4
 ToDo:
   fix ugly hack with loading changed assembly from memory

P.S. Large world creating / crashing-save.zip loading ...
[~mod-injector.zip](https://github.com/ConfuzzedCat/TerrariaInjector/files/10984215/mod-injector.zip)

**Comment by ConfuzzedCat** [comment]
@deltaone Sorry for be radio silence, had stuff taking up my time, and lost a little motivation. I want to say thank you for what you have made and fixed. 
The stuff deltaone has made, seems to be working, so I will put in the Repo, but I will keep the name(TerrariaInjector), but keep a note that it would work with any xna games.
So expect a new release soonish.
